"""
02_parks.py  (was 02-merge-parks-entrances.py)
Merges park polygons from configured sources, clips to study boundary,
and extracts park entrances via OSM road intersection method.

Inputs:
    config.PARK_SOURCES (list of source dicts)
    data/osm/{CITY}_study_area_boundary.shp
    data/osm/{CITY}_osm_edges.shp
    data/osm/{CITY}_walk.graphml

Outputs:
    data/parks/processed/{CITY}_parks_merged.shp
    data/parks/processed/{CITY}_parks_merged.csv
    data/parks/processed/{CITY}_park_entrances.shp
    outputs/figures/{CITY}_parks_merged_check.png
    outputs/figures/{CITY}_entrances_check.png

Notes:
    After running, open outputs/figures/entrance_review/ maps generated by
    tools/entrance_review.py to check flagged parks before proceeding to 03.
"""

import os
import sys
import glob

_SCRIPTS_DIR = os.path.dirname(os.path.abspath(__file__))
if _SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, _SCRIPTS_DIR)
import config
os.chdir(config.REPO_DIR)

import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import osmnx as ox

CITY       = config.CITY
OUTPUT_DIR = 'data/parks/processed'
FIG_DIR    = 'outputs/figures'
os.makedirs(OUTPUT_DIR, exist_ok=True)
os.makedirs(FIG_DIR, exist_ok=True)

BOUNDARY_PATH = f'data/osm/{CITY}_study_area_boundary.shp'
EDGES_PATH    = f'data/osm/{CITY}_osm_edges.shp'
GRAPH_PATH    = f'data/osm/{CITY}_walk.graphml'


# %% 1. LOAD AND MERGE PARK POLYGONS
print("Loading and merging park polygon sources...")
frames = []
for src in config.PARK_SOURCES:
    path = src['path']
    # Resolve directory to first *.shp found
    if os.path.isdir(path):
        shp_files = glob.glob(os.path.join(path, '*.shp'))
        assert shp_files, f"No .shp found in {path}"
        path = shp_files[0]

    gdf = gpd.read_file(path).to_crs(config.CRS)
    gdf['source']    = src['name']
    gdf['park_name'] = gdf[src['name_col']]
    gdf = gdf[['geometry', 'source', 'park_name']].copy()

    if src.get('dissolve', False):
        gdf = gdf.dissolve(by='park_name', aggfunc='first').reset_index()

    print(f"  {src['name']}: {len(gdf)} parks loaded")
    frames.append(gdf)

parks_all = gpd.GeoDataFrame(
    pd.concat(frames, ignore_index=True),
    crs=config.CRS
)
parks_all = parks_all[parks_all.geometry.is_valid & ~parks_all.geometry.is_empty].copy()
parks_all['area_ha'] = parks_all.geometry.area / 10_000
print(f"\nTotal merged: {len(parks_all)}")
print(f"Geometry types:\n{parks_all.geometry.geom_type.value_counts().to_string()}")


# %% 2. FILTER, CLIP, AND ASSIGN IDs
print("\nFiltering and clipping...")
boundary = gpd.read_file(BOUNDARY_PATH).to_crs(config.CRS)

parks_filtered = parks_all[
    (parks_all['area_ha'] >= config.MIN_AREA_HA) |
    (parks_all['park_name'].isin(config.EXPLICIT_INCLUDE))
].copy()
print(f"After size filter + explicit includes: {len(parks_filtered)}")

parks_clipped = gpd.clip(parks_filtered, boundary).reset_index(drop=True)
parks_clipped['area_ha'] = parks_clipped.geometry.area / 10_000

parks_clipped = parks_clipped[
    (parks_clipped['area_ha'] >= config.MIN_AREA_HA) |
    (parks_clipped['park_name'].isin(config.EXPLICIT_INCLUDE))
].copy().reset_index(drop=True)
print(f"After post-clip filter: {len(parks_clipped)}")

parks_clipped = parks_clipped[parks_clipped['park_name'].notna()].copy()
parks_clipped = parks_clipped[
    ~parks_clipped['park_name'].isin(config.EXCLUDE_PARKS)
].copy().reset_index(drop=True)

parks_clipped['park_id'] = (
    parks_clipped['source'] + '_' + parks_clipped.index.astype(str)
)

print(f"\nFinal park count: {len(parks_clipped)}")
print(f"Source breakdown:\n{parks_clipped['source'].value_counts().to_string()}")
print(f"\nExplicit includes confirmed:")
print(parks_clipped[parks_clipped['park_name'].isin(config.EXPLICIT_INCLUDE)]
      [['park_id', 'park_name', 'area_ha']])

overlap = gpd.overlay(parks_clipped, parks_clipped, how='intersection')
overlap = overlap[overlap['park_id_1'] != overlap['park_id_2']]
print(f"\nOverlapping park pairs: {len(overlap)}")

parks_clipped.to_file(f"{OUTPUT_DIR}/{CITY}_parks_merged.shp")
parks_clipped[['park_id', 'source', 'park_name', 'area_ha']].to_csv(
    f"{OUTPUT_DIR}/{CITY}_parks_merged.csv", index=False
)
print(f"Saved {CITY}_parks_merged.shp/.csv")


# %% 3. EXTRACT AND DEDUPLICATE ENTRANCES
print("\nLoading OSM network and edges...")
G     = ox.load_graphml(GRAPH_PATH)
edges = gpd.read_file(EDGES_PATH)
assert parks_clipped.crs == edges.crs, "CRS mismatch"

parks_buffered = parks_clipped.copy()
parks_buffered['geometry'] = parks_clipped.apply(
    lambda row: row.geometry.boundary.buffer(
        config.PARK_BUFFERS.get(row['park_name'], config.BUFFER_M)
    ), axis=1
)

joined = gpd.sjoin(
    edges[['geometry']].reset_index().rename(columns={'index': 'edge_idx'}),
    parks_buffered[['park_id', 'park_name', 'source', 'area_ha', 'geometry']],
    how='inner',
    predicate='intersects'
)
print(f"Edge-park intersections: {len(joined)}")

entrance_records = []
parks_buffered_idx = parks_buffered.set_index('park_id')

for _, row in joined.iterrows():
    edge_geom = edges.iloc[row['edge_idx']].geometry
    park_geom = parks_buffered_idx.loc[row['park_id'], 'geometry']
    intersection = edge_geom.intersection(park_geom)

    if intersection.is_empty:
        continue

    if intersection.geom_type == 'Point':
        pts = [intersection]
    elif intersection.geom_type == 'MultiPoint':
        pts = list(intersection.geoms)
    elif intersection.geom_type in ('LineString', 'MultiLineString'):
        pts = [intersection.interpolate(0.5, normalized=True)]
    else:
        pts = [intersection.centroid]

    for pt in pts:
        entrance_records.append({
            'park_id':   row['park_id'],
            'park_name': row['park_name'],
            'source':    row['source'],
            'area_ha':   row['area_ha'],
            'geometry':  pt
        })

entrances_raw = gpd.GeoDataFrame(entrance_records, crs=parks_clipped.crs)
print(f"Raw entrance points: {len(entrances_raw)}")

deduped = []
for park_id, group in entrances_raw.groupby('park_id'):
    group = group.copy().reset_index(drop=True)
    used  = [False] * len(group)

    for i in range(len(group)):
        if used[i]:
            continue
        cluster = [i]
        for j in range(i + 1, len(group)):
            if not used[j]:
                if group.geometry.iloc[i].distance(group.geometry.iloc[j]) <= config.DEDUP_M:
                    cluster.append(j)
                    used[j] = True
        used[i] = True

        rep_point = group.geometry.iloc[cluster].union_all().centroid
        deduped.append({
            'park_id':   park_id,
            'park_name': group['park_name'].iloc[0],
            'source':    group['source'].iloc[0],
            'area_ha':   group['area_ha'].iloc[0],
            'geometry':  rep_point
        })

entrances = gpd.GeoDataFrame(deduped, crs=parks_clipped.crs).reset_index(drop=True)
print(f"Entrances after dedup: {len(entrances_raw)} → {len(entrances)} "
      f"({100*(1 - len(entrances)/len(entrances_raw)):.1f}% removed)")

parks_with_entrances = entrances['park_id'].unique()
parks_no_entrance = parks_clipped[~parks_clipped['park_id'].isin(parks_with_entrances)]
print(f"\nParks with 0 entrances: {len(parks_no_entrance)} <- review manually")
if len(parks_no_entrance) > 0:
    print(parks_no_entrance[['park_id', 'park_name', 'area_ha']].to_string())


# %% 4. SNAP TO OSM NODES AND SAVE
print("\nSnapping entrances to nearest OSM node...")
nodes_gdf = ox.graph_to_gdfs(G, edges=False)[['geometry']].to_crs(config.CRS)

entrances_4326 = entrances.to_crs('EPSG:4326')
entrances['nearest_node'] = ox.distance.nearest_nodes(
    G,
    entrances_4326.geometry.x.values,
    entrances_4326.geometry.y.values
)

entrances['snap_dist_m'] = [
    entrances.geometry.iloc[i].distance(
        nodes_gdf.loc[entrances['nearest_node'].iloc[i], 'geometry']
    )
    for i in range(len(entrances))
]

print(f"Snap distance — mean: {entrances['snap_dist_m'].mean():.1f}m, "
      f"median: {entrances['snap_dist_m'].median():.1f}m, "
      f"max: {entrances['snap_dist_m'].max():.1f}m")
if entrances['snap_dist_m'].max() > 50:
    print("WARNING: some entrances snap >50m — review:")
    print(entrances.nlargest(5, 'snap_dist_m')[['park_name', 'snap_dist_m']])

ent_per_park = entrances.groupby('park_id').size()
print(f"\nEntrances per park — mean: {ent_per_park.mean():.1f}, "
      f"median: {ent_per_park.median():.1f}, max: {ent_per_park.max()}")
print(f"Parks with >20 entrances: {(ent_per_park > 20).sum()}")

valid_nodes = set(G.nodes())
invalid = entrances[~entrances['nearest_node'].isin(valid_nodes)]
print(f"Entrances with invalid nearest_node: {len(invalid)}")

entrances['entrance_id'] = entrances.index + 1
entrances[['entrance_id', 'park_id', 'park_name', 'source',
           'area_ha', 'nearest_node', 'snap_dist_m', 'geometry']].to_file(
    f"{OUTPUT_DIR}/{CITY}_park_entrances.shp"
)
print(f"Saved {CITY}_park_entrances.shp")
print("\nTo review flagged parks run: python scripts/tools/entrance_review.py")


# %% 5. VALIDATION MAPS
colours = {}
for i, src in enumerate(config.PARK_SOURCES):
    default_colours = ['#2ca25f', '#2b8cbe', '#d95f0e', '#984ea3']
    colours[src['name']] = default_colours[i % len(default_colours)]

fig, ax = plt.subplots(figsize=(12, 10))
boundary_3857 = boundary.to_crs(epsg=3857)
parks_3857    = parks_clipped.to_crs(epsg=3857)
boundary_3857.boundary.plot(ax=ax, color='black', linewidth=0.8, linestyle='--')
for source, colour in colours.items():
    subset = parks_3857[parks_3857['source'] == source]
    if len(subset):
        subset.plot(ax=ax, color=colour, alpha=0.6, edgecolor='white', linewidth=0.3)
patches = [mpatches.Patch(color=c, label=s, alpha=0.6) for s, c in colours.items()]
ax.legend(handles=patches, loc='upper left')
ax.set_title(f'Merged Park Polygons — {CITY.title()} Study Area\n'
             f'n={len(parks_clipped)}, area ≥{config.MIN_AREA_HA} ha')
ax.set_axis_off()
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/{CITY}_parks_merged_check.png", dpi=150, bbox_inches='tight')
plt.close()

fig, ax = plt.subplots(figsize=(12, 10))
entrances_3857 = entrances.to_crs(epsg=3857)
parks_3857.plot(ax=ax, color='#e0ede0', edgecolor='#2ca25f', linewidth=0.5)
entrances_3857.plot(ax=ax, color='#d95f0e', markersize=2, alpha=0.6)
ax.set_title(f'Park Entrances — {CITY.title()}\n'
             f'n={len(entrances)} entrances, {len(parks_clipped)} parks')
ax.set_axis_off()
plt.tight_layout()
plt.savefig(f"{FIG_DIR}/{CITY}_entrances_check.png", dpi=150, bbox_inches='tight')
plt.close()

print("Validation maps saved.")
print("\nDone.")
